import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fluxion, FluxionWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Configure Sentry for production error tracking
config :sentry,
  environment_name: :prod,
  traces_sample_rate: 0.2,
  enable_source_code_context: true,
  client: RateCalculator.SentryReqClient

# Configure Logger to include Sentry backend in production and only log info+
config :logger,
  level: :info,
  backends: [:console, Sentry.LoggerBackend]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
